@startuml
skinparam linetype ortho
skinparam rectangle {
    BackgroundColor<<external>> LightBlue
    BackgroundColor<<internal>> LightGreen
    BackgroundColor<<subprocesses>> LightYellow
    Padding 20
    MinWidth 300
}

rectangle "Waymo Open Dataset Database" <<external>> {
    [WaymoPointCloud]
}

rectangle "Point Cloud Processing Module" <<internal>> {
    [Convert to ROS Pointcloud]
    rectangle "Point Cloud Processing" <<subprocesses>> {
        [crop]
        [downsampling]
        [groundExtraction]
        [clustering]
    }
}

rectangle "Data Association Module" <<internal>> {
    [Receive Processed PointCloud]
}

[WaymoPointCloud] --> [Convert to ROS Pointcloud] : pointcloud
[Convert to ROS Pointcloud] -right-> [crop] : ROS pointcloud
[crop] --> [downsampling] : cropped pointcloud
[downsampling] --> [groundExtraction] : downsampled pointcloud
[groundExtraction] --> [clustering] : ground extracted pointcloud
[clustering] --> [Receive Processed PointCloud] : clustered pointcloud

@enduml
