@startuml
skinparam linetype ortho
skinparam rectangle {
    BackgroundColor<<external>> LightBlue
    BackgroundColor<<internal>> LightGreen
    BackgroundColor<<system>> White
    BackgroundColor<<subprocesses>> LightYellow
    Padding 20
    MinWidth 300
}

'--- Landmark Detection System ---
rectangle "Waymo Client Module" <<internal>> {
    [Receive Clustered Point Cloud]
    [Receive Processed Image]
    rectangle "Data Association Module" <<subprocesses>> {
        [Project Point Cloud On Image]
        [Calculate IoU]
        [Get Landmark Poses in Vehicle Frame]
    }
}


' '--- Data Association Flow ---
[Receive Clustered Point Cloud] -down-> [Project Point Cloud On Image] : clustered_pointcloud
[Receive Processed Image] -down-> [Project Point Cloud On Image] : processed_image
[Project Point Cloud On Image] -down-> [Calculate IoU] : projection_data
[Calculate IoU] -down-> [Get Landmark Poses in Vehicle Frame] : matched_clusters


@enduml