@startuml
skinparam rectangle {
    BackgroundColor<<external>> LightBlue
}

actor User

rectangle "Point Cloud Processing Module" {
    rectangle "PointCloudProcessor" {
        [Initialize]
        [ProcessPointCloudService]
        [AdvertiseService]
    }
}

rectangle "Waymo Open Dataset Database" <<external>> {
    [WaymoPointCloud]
}

rectangle "Data Association Module" <<external>> {
    [ReceiveProcessedPointCloud]
}

User -> [Initialize]
[WaymoPointCloud] -> [ProcessPointCloudService] : produces
[ProcessPointCloudService] -> [ReceiveProcessedPointCloud] : sends processed pointcloud

@enduml
