@startuml
[*] --> Inicio
state Inicio {
    [*] --> Extraccion
}
state Extraccion {
    Extraccion : Extraer puntos de sensores
    Extraccion --> CrearVoxelGrid
}

state CrearVoxelGrid {
    CrearVoxelGrid : Crear VoxelGrid
    CrearVoxelGrid --> DefinirLeafSize
}

state DefinirLeafSize {
    DefinirLeafSize : Definir leafSize (tamaño de los voxeles)
    DefinirLeafSize --> DefinirMinPointsVoxel
}

state DefinirMinPointsVoxel {
    DefinirMinPointsVoxel : Definir minPointsVoxel (mínimo de puntos por voxel)
    DefinirMinPointsVoxel --> AplicarFiltro
}

state AplicarFiltro {
    AplicarFiltro : Aplicar filtro
    AplicarFiltro --> GenerarNubesReducidas
}

state GenerarNubesReducidas {
    GenerarNubesReducidas : Generar nubes de puntos reducidas
    GenerarNubesReducidas --> Fin
}

state Fin {
    [*] --> Fin
}

Inicio --> Extraccion
Extraccion --> CrearVoxelGrid
CrearVoxelGrid --> DefinirLeafSize
DefinirLeafSize --> DefinirMinPointsVoxel
DefinirMinPointsVoxel --> AplicarFiltro
AplicarFiltro --> GenerarNubesReducidas
GenerarNubesReducidas --> Fin
@enduml
