@startuml
skinparam linetype ortho
skinparam monochrome true
skinparam classBackgroundColor white

entity Frame {
    * timestamp_micros: int64
    * map_pose_offset: (x: double, y: double, z: double)
}

entity Pose {
    * transform: double[]
}

entity CameraImage {
    * name: string
    * image: bytes
    * pose_timestamp: double
    * velocity
    * shutter: double
    * camera_trigger_time: double
    * camera_readout_done_time: double
    * camera_segmentation_label
}

entity CameraCalibration {
    * name: CameraName.Name
    * intrinsic: double[]
    * extrinsic: { transform: double[] }
    * width: int32
    * height: int32
    * rolling_shutter_direction: RollingShutterDirection
}

entity LaserCalibration {
    * name: LaserName.Name
    * beam_inclinations: double[]
    * beam_inclination_min: double
    * beam_inclination_max: double
    * extrinsic: { transform: double[] }
}

entity Context {
    * name: string
    * Stats: message
}


Frame --> "0..1" Pose
Frame --> "0..1" Context
Frame --> "0..*" CameraImage
CameraImage --> "0..1" Pose
Context --> "0..*" CameraCalibration
Context --> "0..*" LaserCalibration
CameraCalibration --> "0..1" Pose
LaserCalibration --> "0..1" Pose
@enduml
